In [4]:
import torch
torch.__version__

'2.4.0+cu121'

In [10]:
import torch
scaler = torch.tensor(3)
scaler, scaler.ndim, scaler.item()

(tensor(3), 0, 3)

In [12]:
vector=torch.tensor([1,2])
vector, vector.ndim, vector.shape

(tensor([1, 2]), 1, torch.Size([2]))

In [19]:
#Matrix
matrix=torch.tensor([[1,2],[3,4]])
matrix, matrix.ndim, matrix.shape,matrix[0],matrix[1]

(tensor([[1, 2],
         [3, 4]]),
 2,
 torch.Size([2, 2]),
 tensor([1, 2]),
 tensor([3, 4]))

In [33]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([2, 3, 3]))

In [31]:
TENSOR[0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])